[platformio]
default_envs = esp32cam

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -I../../shared/include
lib_extra_dirs =
    ../../
build_src_filter =
    +<*>
